### PR TITLE
chore: get rid of npmrc generator

### PR DESCRIPTION
**Pull request by FezVrasta**
## PR checklist

- [x] I have followed the ["Committing and publishing"](https://github.com/quid/refraction/blob/master/CONTRIBUTING.md) guidelines;
- [x] I have added unit tests to cover my changes;
- [x] I updated the documentation and examples accordingly;

## Changes description

We used to generate the `.npmrc` file ad deploy time, writing into it the auth token, we don't actually need any of that, we can rely on the environment variables expansion feature of Yarn and npm to replace `${AUTOMATED_WRITE_AUTH}` with its value at evaluation time.

### CODE REVIEW

**Comment by FezVrasta** [comment]
This needs some work, right now if the env variable is not defined, Yarn throws an error because it can't expand it properly.

**Comment by wuhao1117** [comment]
That looks very clean. Does it only work with public npm registry?

**Comment by FezVrasta** [comment]
No it works with any registry

**Comment by wuhao1117** [comment]
How is the `${AUTOMATED_WRITE_AUTH}` provided to npmrc at runtime?

**Comment by FezVrasta** [comment]
Yarn and npm automatically expand it reading the environment variables, it's a feature of the above mentioned tools.

**Comment by wuhao1117** [comment]
> Yarn and npm automatically expand it reading the environment variables, it's a feature of the above mentioned tools.

I see. That's very neat. I was just reading [npmrc doc](https://docs.npmjs.com/files/npmrc) and was surprised we neglected this builtin feature before.

**Pull request closed without merging**
